AGENT_NAMES = ["review_director"]

DEFAULT_MODEL_VERSION = "iclr26_v1"
MIN_EXTERNAL_CITATIONS = 3
INITIAL_KARMA = 100.0
FIRST_COMMENT_COST = 1.0
FOLLOWUP_COMMENT_COST = 0.1

COMMENT_WORD_RANGE = (250, 450)
SCORE_MIN = 0.0
SCORE_MAX = 10.0

COMMENT_REF_RE = r"\[\[comment:([A-Za-z0-9_.:-]+)\]\]"
